// Mocks generated by Mockito 5.4.6 from annotations
// in studymate_flutter/test/unit/providers/auth_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:studymate_flutter/models/ai_response.dart' as _i5;
import 'package:studymate_flutter/models/study_goal.dart' as _i3;
import 'package:studymate_flutter/models/study_session.dart' as _i4;
import 'package:studymate_flutter/models/user.dart' as _i2;
import 'package:studymate_flutter/services/api_service.dart' as _i6;
import 'package:studymate_flutter/services/local_storage_service.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStudyGoal_1 extends _i1.SmartFake implements _i3.StudyGoal {
  _FakeStudyGoal_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStudySession_2 extends _i1.SmartFake implements _i4.StudySession {
  _FakeStudySession_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAIResponse_3 extends _i1.SmartFake implements _i5.AIResponse {
  _FakeAIResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i6.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setAuthToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #setAuthToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearAuthToken() => super.noSuchMethod(
        Invocation.method(
          #clearAuthToken,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<Map<String, dynamic>> register(
    String? email,
    String? password,
    String? name, {
    String? username,
    String? passwordConfirm,
    bool? termsAccepted = true,
    bool? privacyAccepted = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            email,
            password,
            name,
          ],
          {
            #username: username,
            #passwordConfirm: passwordConfirm,
            #termsAccepted: termsAccepted,
            #privacyAccepted: privacyAccepted,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> socialLogin(
          Map<String, dynamic>? socialData) =>
      (super.noSuchMethod(
        Invocation.method(
          #socialLogin,
          [socialData],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> refreshToken(String? refreshToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [refreshToken],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> requestPasswordReset(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestPasswordReset,
          [email],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> confirmPasswordReset({
    required String? token,
    required String? password,
    required String? passwordConfirm,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmPasswordReset,
          [],
          {
            #token: token,
            #password: password,
            #passwordConfirm: passwordConfirm,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<_i2.User> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i7.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i7.Future<_i2.User>);

  @override
  _i7.Future<_i2.User> updateProfile(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [data],
        ),
        returnValue: _i7.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #updateProfile,
            [data],
          ),
        )),
      ) as _i7.Future<_i2.User>);

  @override
  _i7.Future<List<_i3.StudyGoal>> getGoals() => (super.noSuchMethod(
        Invocation.method(
          #getGoals,
          [],
        ),
        returnValue: _i7.Future<List<_i3.StudyGoal>>.value(<_i3.StudyGoal>[]),
      ) as _i7.Future<List<_i3.StudyGoal>>);

  @override
  _i7.Future<_i3.StudyGoal> createGoal(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #createGoal,
          [data],
        ),
        returnValue: _i7.Future<_i3.StudyGoal>.value(_FakeStudyGoal_1(
          this,
          Invocation.method(
            #createGoal,
            [data],
          ),
        )),
      ) as _i7.Future<_i3.StudyGoal>);

  @override
  _i7.Future<_i3.StudyGoal> updateGoal(
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateGoal,
          [
            id,
            data,
          ],
        ),
        returnValue: _i7.Future<_i3.StudyGoal>.value(_FakeStudyGoal_1(
          this,
          Invocation.method(
            #updateGoal,
            [
              id,
              data,
            ],
          ),
        )),
      ) as _i7.Future<_i3.StudyGoal>);

  @override
  _i7.Future<void> deleteGoal(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteGoal,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i4.StudySession>> getSessions() => (super.noSuchMethod(
        Invocation.method(
          #getSessions,
          [],
        ),
        returnValue:
            _i7.Future<List<_i4.StudySession>>.value(<_i4.StudySession>[]),
      ) as _i7.Future<List<_i4.StudySession>>);

  @override
  _i7.Future<_i4.StudySession> startSession(String? goalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #startSession,
          [goalId],
        ),
        returnValue: _i7.Future<_i4.StudySession>.value(_FakeStudySession_2(
          this,
          Invocation.method(
            #startSession,
            [goalId],
          ),
        )),
      ) as _i7.Future<_i4.StudySession>);

  @override
  _i7.Future<_i4.StudySession> endSession(String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #endSession,
          [sessionId],
        ),
        returnValue: _i7.Future<_i4.StudySession>.value(_FakeStudySession_2(
          this,
          Invocation.method(
            #endSession,
            [sessionId],
          ),
        )),
      ) as _i7.Future<_i4.StudySession>);

  @override
  _i7.Future<_i5.AIResponse> chatWithAI(
    String? message, {
    String? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #chatWithAI,
          [message],
          {#context: context},
        ),
        returnValue: _i7.Future<_i5.AIResponse>.value(_FakeAIResponse_3(
          this,
          Invocation.method(
            #chatWithAI,
            [message],
            {#context: context},
          ),
        )),
      ) as _i7.Future<_i5.AIResponse>);

  @override
  _i7.Future<Map<String, dynamic>> generateQuiz(
    String? topic,
    int? questionCount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateQuiz,
          [
            topic,
            questionCount,
          ],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> generateStudyPlan(
    String? goal,
    int? days,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateStudyPlan,
          [
            goal,
            days,
          ],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> getStatistics({String? period}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
          {#period: period},
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> getProgressReport(String? goalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProgressReport,
          [goalId],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> testConnection() => (super.noSuchMethod(
        Invocation.method(
          #testConnection,
          [],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> testHealth() => (super.noSuchMethod(
        Invocation.method(
          #testHealth,
          [],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> testPost(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #testPost,
          [data],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<_i2.User> updateUser(Map<String, dynamic>? userData) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [userData],
        ),
        returnValue: _i7.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #updateUser,
            [userData],
          ),
        )),
      ) as _i7.Future<_i2.User>);

  @override
  _i7.Future<List<_i3.StudyGoal>> getStudyGoals() => (super.noSuchMethod(
        Invocation.method(
          #getStudyGoals,
          [],
        ),
        returnValue: _i7.Future<List<_i3.StudyGoal>>.value(<_i3.StudyGoal>[]),
      ) as _i7.Future<List<_i3.StudyGoal>>);

  @override
  _i7.Future<List<_i4.StudySession>> getStudySessions({
    String? goalId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStudySessions,
          [],
          {
            #goalId: goalId,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i7.Future<List<_i4.StudySession>>.value(<_i4.StudySession>[]),
      ) as _i7.Future<List<_i4.StudySession>>);

  @override
  _i7.Future<_i3.StudyGoal> createStudyGoal(Map<String, dynamic>? goalData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStudyGoal,
          [goalData],
        ),
        returnValue: _i7.Future<_i3.StudyGoal>.value(_FakeStudyGoal_1(
          this,
          Invocation.method(
            #createStudyGoal,
            [goalData],
          ),
        )),
      ) as _i7.Future<_i3.StudyGoal>);

  @override
  _i7.Future<_i3.StudyGoal> updateStudyGoal(
    String? goalId,
    Map<String, dynamic>? goalData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStudyGoal,
          [
            goalId,
            goalData,
          ],
        ),
        returnValue: _i7.Future<_i3.StudyGoal>.value(_FakeStudyGoal_1(
          this,
          Invocation.method(
            #updateStudyGoal,
            [
              goalId,
              goalData,
            ],
          ),
        )),
      ) as _i7.Future<_i3.StudyGoal>);

  @override
  _i7.Future<void> deleteStudyGoal(String? goalId) => (super.noSuchMethod(
        Invocation.method(
          #deleteStudyGoal,
          [goalId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i4.StudySession> createStudySession(
          Map<String, dynamic>? sessionData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStudySession,
          [sessionData],
        ),
        returnValue: _i7.Future<_i4.StudySession>.value(_FakeStudySession_2(
          this,
          Invocation.method(
            #createStudySession,
            [sessionData],
          ),
        )),
      ) as _i7.Future<_i4.StudySession>);

  @override
  _i7.Future<_i4.StudySession> updateStudySession(
    String? sessionId,
    Map<String, dynamic>? sessionData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStudySession,
          [
            sessionId,
            sessionData,
          ],
        ),
        returnValue: _i7.Future<_i4.StudySession>.value(_FakeStudySession_2(
          this,
          Invocation.method(
            #updateStudySession,
            [
              sessionId,
              sessionData,
            ],
          ),
        )),
      ) as _i7.Future<_i4.StudySession>);

  @override
  _i7.Future<_i5.AIResponse> askAI(
    String? query, {
    _i5.AIResponseType? type,
    Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #askAI,
          [query],
          {
            #type: type,
            #context: context,
          },
        ),
        returnValue: _i7.Future<_i5.AIResponse>.value(_FakeAIResponse_3(
          this,
          Invocation.method(
            #askAI,
            [query],
            {
              #type: type,
              #context: context,
            },
          ),
        )),
      ) as _i7.Future<_i5.AIResponse>);

  @override
  _i7.Future<List<_i5.AIResponse>> getAIHistory({int? limit}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAIHistory,
          [],
          {#limit: limit},
        ),
        returnValue: _i7.Future<List<_i5.AIResponse>>.value(<_i5.AIResponse>[]),
      ) as _i7.Future<List<_i5.AIResponse>>);

  @override
  _i7.Future<Map<String, dynamic>> getStudyStatistics({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStudyStatistics,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i8.LocalStorageService {
  MockLocalStorageService() {
    _i1.throwOnMissingStub(this);
  }
}
